Property Get AdaptiveMenu() As Boolean
End Property
Property Let AdaptiveMenu()
End Property

Property Get Application() As Object
End Property

Property Get BuiltIn() As Boolean
End Property

Property Get Context() As String
End Property
Property Let Context()
End Property

Property Get Controls() As CommandBarControls
End Property

Property Get Creator() As Long
End Property

Property Get Enabled() As Boolean
End Property
Property Let Enabled()
End Property

Property Get Height() As Long
End Property
Property Let Height()
End Property

Property Get Index() As Long
End Property

Property Get Left() As Long
End Property
Property Let Left()
End Property

Property Get Name() As String
End Property
Property Let Name()
End Property

Property Get NameLocal() As String
End Property
Property Let NameLocal()
End Property

Property Get Parent() As Object
End Property

Property Get Position() As MsoBarPosition
End Property
Property Let Position()
End Property

Property Get Protection() As MsoBarProtection
End Property
Property Let Protection()
End Property

Property Get RowIndex() As Long
End Property
Property Let RowIndex()
End Property

Property Get Top() As Long
End Property
Property Let Top()
End Property

Property Get Type() As MsoBarType
End Property

Property Get Visible() As Boolean
End Property
Property Let Visible()
End Property

Property Get Width() As Long
End Property
Property Let Width()
End Property

Sub Delete()
End Sub

Function FindControl(Optional Type, Optional Id, Optional Tag, Optional Visible, Optional Recursive) As CommandBarControl
End Function

Sub Reset()
End Sub

Sub ShowPopup(Optional x, Optional y)
End Sub