Property Get Application() As Application
End Property

Property Get CLSID() As String
End Property

Property Get Creator() As XlCreator
End Property

Property Get FullName() As String
End Property

Property Get Installed() As Boolean
End Property
Property Let Installed() As Boolean
End Property

Property Get IsOpen() As Boolean
End Property

Property Get Name() As String
End Property

Property Get Parent() As Object
End Property

Property Get Path() As String
End Property

Property Get progID() As String
End Property